apiVersion: v1
kind: Service
metadata:
  namespace: eis
  name: eis-client-service
  labels:
    run: eis-client-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: eis-client
