apiVersion: v1
kind: Service
metadata:
  namespace: eis
  name: eis-server-service
  labels:
    run: eis-server-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: eis-server
