# Application Settings
# Database settings
# Backend settings
eis-backend:
  image:
    repository: "eisapps.azurecr.io/eisbackend"
    tag: "33e68fdba15cc382b4e6c4a41d99435787cd4c54"
    pullPolicy: "Always"
    pullSecretName: "acrsecret"
  env:
    TYPEORM_CONNECTION: postgres
    TYPEORM_PORT: "5432"
    TYPEORM_USERNAME: postgres
    TYPEORM_PASSWORD: eis
    TYPEORM_DATABASE: eis
    TYPEORM_SYNCHRONIZE: "true"
    TYPEORM_LOGGING: "true"
    PORT: "3000"
    SECRET_KEY: secretKey
    LOG_FORMAT: dev
    JWT_TOKEN: qazxsw2!QAZXSW@<yS<BF%Jxa4L3bt2w`%T'VYn_SxP9e?{
    TOKEN_EXPIRY_DAYS: "1"
    SOURCE_EMAIL_ADDRESS: notifications@team-eagle.ca
    EMAIL_SERVER_NAME: smtp.office365.com
    EMAIL_SERVER_PORT: "587"
    EMAIL_USER_NAME: notifications@team-eagle.ca
    EMAIL_PASSWORD: hhtbcpwdkfvmfwjf
    EIS_USER_TYPE_PASSWORD: bw
    NAV_TEST_SERVER: https://rsctest.navcanada.ca/rsc/rscservice.asmx
    NAV_PRODUCTION_SERVER: https://nes.navcanada.ca/RSCService.asmx
    NAV_TEST_SERVER_USERNAME: vendor_Eagle
    NAV_TEST_SERVER_PASSWORD: 4rfv$RFV
    synchronize: "false"

# Frontend settings
eis-frontend:
  # Image
  image:
    repository: "eisapps.azurecr.io/eisfrontend"
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "33e68fdba15cc382b4e6c4a41d99435787cd4c54"
    pullSecretName: "acrsecret"

  # Service
  service:
    type: LoadBalancer
    port: 80
    targetPort: 80

  # Ingress
  ingress:
    enabled: false
    className: ""
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []

# Monitoring Settings
monitoring:
  enabled: false

# On Premise LoadBalancer
metallb:
  enabled: false
  configInline: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 
postgresql:
  global:
    postgresql:
      auth:
        postgresPassword: "eis"
        username: "postgres"
        password: "eis"
        database: "eis"
