---
- name: Create Secret for ACR in Kubernetes
  hosts: localhost
  gather_facts: false

  vars:
    tenant_id: "406a2a33-7202-4bc5-adff-234a0a445457"
    subscription_id: "d6389ac0-7ed9-4150-8282-9a7cb554e4bd"
    client_id: "e0b1a8ac-d80a-4ada-ba91-3605dde8b9aa"
    client_secret: "Eoj8Q~SPzYENF695jS7585H-oJrUsregWEFNTddf"
    acr_name: "EIS"

  tasks:
    - name: Install required packages
      become: true
      apt:
        name: azure-cli
        state: present
      when: ansible_distribution == 'Ubuntu'  # Update this based on your target OS
      ignore_errors: true

    - name: Login to Azure
      shell: az login --service-principal --tenant "{{ tenant_id }}" --subscription "{{ subscription_id }}" --username "{{ client_id }}" --password "{{ client_secret }}"
      changed_when: false
      ignore_errors: true

    - name: Get ACR login server
      shell: az acr show --name "{{ acr_name }}" --query loginServer --output tsv
      register: acr_login_server

    - name: Get ACR credentials
      shell: az acr credential show --name "{{ acr_name }}" --query "join(';', [username, passwords[0].value])" --output tsv
      register: acr_credentials

    - name: Create Secret in Kubernetes
      k8s:
        api_version: v1
        kind: Secret
        namespace: default
        name: acr-secret
        type: kubernetes.io/dockerconfigjson
        data:
          .dockerconfigjson: "{{ acr_credentials.stdout }}"
